In [343]:
import torch
x: torch.Tensor = torch.tensor([3.0])
y: torch.Tensor = torch.tensor([2.0])

x + y

tensor([5.])

In [344]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [345]:
x[3]

tensor(3)

In [346]:
len(x)

4

In [347]:
A: torch.Tensor = torch.arange(20).reshape((4, 5))
A.T

tensor([[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]])

In [348]:
B: torch.Tensor = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [349]:
x = torch.arange(24).reshape((2, 3, 4))
x[1][2][3]

tensor(23)

In [350]:
A = torch.arange(20, dtype=torch.int64).reshape((5, 4))
B = A.clone()


In [351]:
A * B

tensor([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121],
        [144, 169, 196, 225],
        [256, 289, 324, 361]])

In [352]:
A = A.reshape(2, 2, 5)
A = A.type(torch.float32)

In [353]:
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
x, y, x.dot(y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [354]:
A = torch.arange(20, dtype=torch.float32).reshape((5, 4))
B = torch.arange(20, dtype=torch.float32).reshape((4, 5))
A, B, B.matmul(A)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]),
 tensor([[120., 130., 140., 150.],
         [320., 355., 390., 425.],
         [520., 580., 640., 700.],
         [720., 805., 890., 975.]]))

In [355]:
A.norm()

tensor(49.6991)