In [1]:
import torch
x: torch.Tensor = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [2]:
x.requires_grad_(True) # set requires_grad to True to track computation with it
x.grad # None because we haven't done any computation yet

In [3]:
y: torch.Tensor = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [4]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [5]:
x.grad == 4 * x

tensor([True, True, True, True])

In [6]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [7]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [8]:
x.grad.zero_()
y = x * x
u = y.detach() # what is detach doing? 
# detach creates a new tensor, detached from the current graph
# u is a new tensor, u is not a view of y
z = u * x
z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [9]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [11]:
def fun(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size=(), requires_grad=True) # what is size=() doing?
# size=() is a tuple with one element
d = fun(a) # what is d doing?
# d is a tensor, the output of fun(a)
d.backward()

a.grad == d / a # why is this true?
# d / a = 2 * 2 * 2 * ... * 2 * 100 * 2 * 2 * 2 * ... * 2

tensor(False)